 version : '3.8'
 services:
   database:
     image: mysql:8.0
     ports:
       - "3307:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=cerp_root
       - MYSQL_DATABASE=cerp
     volumes:
       - ./.mysql_data:/var/lib/mysql
     networks:
       springboot-mysql-net:
   redis:
     image: redis:6.2
     ports:
       - "6379:6379"
   backend:
     build:
       context: ./
       dockerfile: Dockerfile
     ports:
       - "8080:8080"
     networks:
       springboot-mysql-net:
     environment:
       - MYSQL_HOST=database
       - MYSQL_PORT=3306
       - MYSQL_USER=root
       - MYSQL_PASSWORD=cerp_root
       - SPRING_REDIS_HOST=redis
     depends_on:
       - database
       - redis
 networks:
   springboot-mysql-net: