version : '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_connection
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_DATABASE = cerp
    networks:
      - app_connection
    volumes:
      - ./.mysql_data:/var/lib/mysql

networks:
  app_connection: